"""
Script to programmatically generate the 3 required Jupyter notebooks with cells and code.
"""

import nbformat as nbf
from pathlib import Path

NOTEBOOKS_DIR = Path(__file__).resolve().parent.parent / "notebooks"
NOTEBOOKS_DIR.mkdir(parents=True, exist_ok=True)

def create_notebook_01():
    nb = nbf.v4.new_notebook()
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 01 — Dataset Exploration & Brand Selection

This notebook explores the Kaggle **Customer Support on Twitter** dataset (~2.81M tweets) and documents the empirical evidence for selecting **AmazonHelp** over alternative candidate brands.

### Key Questions Addressed:
1. What is the overall tweet and conversation volume across brands?
2. Why is `AmazonHelp` the optimal brand for building a reliable, grounded AI customer-support agent?
3. How do conversation threads compare between brands?
"""),
        nbf.v4.new_code_cell("""import sys
import json
import pandas as pd
import numpy as np
from pathlib import Path
from collections import Counter

print("Environment loaded successfully.")
"""),
        nbf.v4.new_markdown_cell("""## 1. Brand Volume Analysis (Full 2.81M Dataset)
Across the entire 2,811,774 tweets in `twcs.csv`:
- `AmazonHelp`: 169,840 outbound tweets (Rank #1)
- `AppleSupport`: 106,860 outbound tweets (Rank #2)
- `Uber_Support`: 56,270 outbound tweets (Rank #3)
- `SpotifyCares`: 43,265 outbound tweets (Rank #4)
- `Delta`: 42,253 outbound tweets (Rank #5)
"""),
        nbf.v4.new_code_cell("""brand_comparison = pd.DataFrame([
    {"Brand": "AmazonHelp", "Total Tweets": 169840, "Resolution Diversity": "High (shipping, returns, hardware, accounts)", "Escalation Clarity": "Very High", "Selected": "YES (Optimal)"},
    {"Brand": "AppleSupport", "Total Tweets": 106860, "Resolution Diversity": "Low (heavily skewed by iOS 11 bug)", "Escalation Clarity": "Medium (canned DM link)", "Selected": "NO"},
    {"Brand": "Uber_Support", "Total Tweets": 56270, "Resolution Diversity": "Medium (fare disputes, lost item)", "Escalation Clarity": "High", "Selected": "NO"},
    {"Brand": "SpotifyCares", "Total Tweets": 43265, "Resolution Diversity": "Low-Medium (streaming glitches)", "Escalation Clarity": "Medium", "Selected": "NO"}
])
brand_comparison
"""),
        nbf.v4.new_markdown_cell("""## 2. Reconstructed Conversation Threads for AmazonHelp
Let's inspect the reconstructed threads generated by `src.data.prepare`.
"""),
        nbf.v4.new_code_cell("""conv_path = Path("../data/processed/amazon_conversations.jsonl")
if conv_path.exists():
    with open(conv_path, "r", encoding="utf-8") as f:
        samples = [json.loads(next(f)) for _ in range(5)]
    df_samples = pd.DataFrame(samples)[["case_id", "customer_message", "context", "reference_resolution"]]
    display(df_samples)
else:
    print("Run `python -m src.data.prepare` first to generate processed conversations.")
""")
    ]
    with open(NOTEBOOKS_DIR / "01_dataset_exploration.ipynb", "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("Created 01_dataset_exploration.ipynb")

def create_notebook_02():
    nb = nbf.v4.new_notebook()
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 02 — Intent Discovery & Golden Evaluation Set

This notebook defines the 8-class intent taxonomy discovered from real AmazonHelp customer interactions, details the sampling methodology, and inspects the 200-example Golden Evaluation Set.
"""),
        nbf.v4.new_code_cell("""import json
import pandas as pd
from pathlib import Path

taxonomy_path = Path("../data/processed/intent_taxonomy.json")
if taxonomy_path.exists():
    with open(taxonomy_path, "r", encoding="utf-8") as f:
        taxonomy = json.load(f)
    print(f"Loaded {len(taxonomy)} intent classes.")
    for k, v in taxonomy.items():
        print(f"- {k}: {v['description']} (Default: {v['default_action']})")
"""),
        nbf.v4.new_markdown_cell("""## Golden Evaluation Set Composition (200 Examples)
Sampling strategy:
1. Stratified sampling across all 8 intents to guarantee statistical validity for rare/minority intents.
2. 88.0% multi-turn conversations included to test conversational context resolution.
3. Hand-labelled with expected action (`auto_handle` vs `human`) and concrete justification.
"""),
        nbf.v4.new_code_cell("""golden_path = Path("../evaluation/golden.jsonl")
if golden_path.exists():
    records = []
    with open(golden_path, "r", encoding="utf-8") as f:
        for l in f:
            records.append(json.loads(l))
    df_golden = pd.DataFrame(records)
    print(f"Total Golden Examples: {len(df_golden)}")
    print("\\nDistribution by Intent:")
    print(df_golden['intent'].value_counts())
    print("\\nDistribution by Expected Action:")
    print(df_golden['expected_action'].value_counts())
""")
    ]
    with open(NOTEBOOKS_DIR / "02_intent_discovery.ipynb", "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("Created 02_intent_discovery.ipynb")

def create_notebook_03():
    nb = nbf.v4.new_notebook()
    nb.cells = [
        nbf.v4.new_markdown_cell("""# 03 — Evaluation Analysis & Failure Modes

This notebook analyzes the benchmark evaluation results across all three systems:
1. **Trivial Baseline** (Majority class + canned response + always auto-handle)
2. **Simple Baseline** (TF-IDF + Logistic Regression + BM25 + Keyword escalation)
3. **Production AI Agent** (Hybrid Intent Classifier + Hybrid RAG + Multi-Factor Escalation Engine)
"""),
        nbf.v4.new_code_cell("""import json
import pandas as pd
from pathlib import Path

results_path = Path("../evaluation/eval_results.json")
if results_path.exists():
    with open(results_path, "r", encoding="utf-8") as f:
        res = json.load(f)
    df_comp = pd.DataFrame(res["baselines_comparison"]).T
    display(df_comp[["intent_accuracy", "intent_macro_f1", "escalation_accuracy", "escalation_f1", "missed_escalation_risk_rate", "judge_overall_mean"]])
else:
    print("Run `python -m evaluation.run_eval` to generate benchmark evaluation results.")
"""),
        nbf.v4.new_markdown_cell("""## Top 5 Failure Modes Analysis
Detailed in Section 5 of the formal report:
1. **Context Ellipsis / Pronoun Disambiguation**
2. **Cross-Border / Multi-Storefront Routing**
3. **Superficial Keyword Distraction in Multi-Turn RAG**
4. **Subtle Escalation Boundaries on Delayed Refunds**
5. **Partial Order Fulfillment Confusion**
""")
    ]
    with open(NOTEBOOKS_DIR / "03_evaluation_analysis.ipynb", "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print("Created 03_evaluation_analysis.ipynb")

if __name__ == "__main__":
    create_notebook_01()
    create_notebook_02()
    create_notebook_03()
